# Generated by Django 4.1.7 on 2023-03-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
