# Generated by Django 4.1.7 on 2023-03-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_quantity',
        ),
    ]
